import { test, expect } from "@playwright/test";

test("product types and editable vendor pseudonyms persist without changing saved barcodes", async ({page,request}) => {
  test.setTimeout(90000);
  expect((await request.post("/api/product-types",{data:{name:"Unauthorized"}})).status()).toBe(401);
  await page.goto("/login");
  await page.getByLabel("Username").fill("SNPAdmin");
  await page.getByLabel("Password").fill("SNPRocks");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page).toHaveURL(/inventory/);
  const errors:string[]=[];
  page.on("pageerror",e=>errors.push(e.message));
  const cfg=await (await page.request.get("/api/config")).json();
  const used=new Set(cfg.vendors.map((v:{pseudo_code:string})=>v.pseudo_code));
  const codes:string[]=[];
  for(let n=2000;codes.length<3;n++) {
    const code=n.toString(36).toUpperCase().padStart(3,"0");
    if (!used.has(code)) codes.push(code);
  }
  const stamp=Date.now(),name=`Secret supplier ${stamp}`,renamed=`Private supplier ${stamp}`;
  const type=`Necklaces ${stamp}`,renamedType=`Necklace sets ${stamp}`;
  const origin={Origin:"http://127.0.0.1:3010"};
  await page.getByRole("link",{name:"Settings",exact:true}).click();
  await page.getByLabel("INR per 1 GBP").fill("100");
  await page.getByRole("button",{name:"Save exchange rate"}).click();
  await expect(page.getByRole("status")).toContainText("Exchange rate updated");
  await page.getByLabel("Vendor name").fill(name);
  await page.getByLabel("Vendor code",{exact:true}).fill(codes[0].toLowerCase());
  await page.getByRole("button",{name:"Add vendor",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Vendor added");
  await page.getByRole("button",{name:`Edit ${name}`,exact:true}).click();
  await page.getByLabel("Vendor name").fill(renamed);
  await page.getByLabel("Vendor code",{exact:true}).fill(codes[1]);
  await page.getByRole("button",{name:"Save vendor",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Vendor updated");
  const config=await (await page.request.get("/api/config")).json();
  const vendor=config.vendors.find((v:{name:string})=>v.name===renamed);
  expect(vendor.pseudo_code).toBe(codes[1]);
  expect((await page.request.post("/api/vendors",{headers:origin,data:{name:`Duplicate ${stamp}`,pseudo_code:codes[1]}})).status()).toBe(409);
  expect((await page.request.patch("/api/vendors",{headers:origin,data:{id:vendor.id,pseudo_code:"long"}})).status()).toBe(400);
  await page.getByLabel("Product type name").fill(type);
  await page.getByRole("button",{name:"Add product type",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Product type added");
  await page.getByRole("button",{name:`Edit ${type}`,exact:true}).click();
  await page.getByLabel("Product type name").fill(renamedType);
  await page.getByRole("button",{name:"Save product type",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Product type updated");
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:"test-results/settings-types-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole("link",{name:"Add product",exact:true}).first().click();
  await page.getByLabel("Item name",{exact:true}).fill(`Type test ${stamp}`);
  await page.getByLabel("Vendor",{exact:true}).selectOption({label:renamed});
  await page.getByLabel("Product type",{exact:true}).selectOption({label:renamedType});
  await page.getByLabel("Price per piece (INR)").fill("1000");
  await expect(page.getByLabel("SKU code")).toHaveValue(new RegExp(`^${codes[1]}-BDZDD-\\d{3}$`));
  const sku=await page.getByLabel("SKU code").inputValue();
  const configTypes=await (await page.request.get("/api/config")).json();
  const productType=configTypes.productTypes.find((t:{name:string})=>t.name===renamedType);
  await page.getByRole("button",{name:"Save product",exact:true}).click();
  await expect(page).toHaveURL(/inventory/);
  const row=page.getByRole("row").filter({hasText:`Type test ${stamp}`});
  await expect(row).toContainText(renamedType);
  const products=await (await page.request.get(`/api/products?sku=${sku}`)).json();
  const product=products.products[0];
  expect(product.product_type_id).toBe(productType.id);
  const originalSvg=await (await page.request.get(`/api/products/${product.id}/barcode`)).text();
  await page.getByRole("link",{name:"Settings",exact:true}).click();
  await page.getByRole("button",{name:`Edit ${renamed}`,exact:true}).click();
  await page.getByLabel("Vendor code",{exact:true}).fill(codes[2]);
  await page.getByRole("button",{name:"Save vendor",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Vendor updated");
  await page.getByRole("button",{name:`Archive ${renamedType}`,exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Product type archived");
  await page.goto(`/products/${product.id}`);
  await expect(page.getByLabel("Product type",{exact:true})).toHaveValue(productType.id);
  await expect(page.getByLabel("SKU code")).toHaveValue(sku);
  await page.getByLabel("Item description").fill("Keep archived classification");
  await page.getByRole("button",{name:"Save changes",exact:true}).click();
  await expect(page).toHaveURL(/inventory/);
  expect(await (await page.request.get(`/api/products/${product.id}/barcode`)).text()).toBe(originalSvg);
  await page.getByLabel("Scan barcode or enter SKU").fill(sku);
  await page.getByLabel("Scan barcode or enter SKU").press("Enter");
  await expect(row).toBeVisible();
  await page.goto("/products/new");
  await expect(page.getByLabel("Product type",{exact:true}).locator(`option[value="${productType.id}"]`)).toHaveCount(0);
  await page.getByLabel("Vendor",{exact:true}).selectOption({label:renamed});
  await page.getByLabel("Price per piece (INR)").fill("1000");
  await expect(page.getByLabel("SKU code")).toHaveValue(new RegExp(`^${codes[2]}-BDZDD-\\d{3}$`));
  const invalidType=await page.request.post("/api/products",{headers:origin,data:{...product,item_name:"Should fail",product_type_id:productType.id,sku_token:(await page.request.post("/api/skus",{headers:origin,data:product}).then(r=>r.json())).token}});
  expect(invalidType.status()).toBe(400);
  // Pending reservations using an old code cannot save after a code edit.
  const reservation=await (await page.request.post("/api/skus",{headers:origin,data:product})).json();
  await page.request.patch("/api/vendors",{headers:origin,data:{id:vendor.id,pseudo_code:codes[0]}});
  const stale=await page.request.post("/api/products",{headers:origin,data:{...product,product_type_id:null,sku_token:reservation.token}});
  expect(stale.status()).toBe(409);
  expect(errors).toEqual([]);
});
